name: Deploy MuleSoft APIs

on:
  workflow_dispatch: # Allow manual triggering of the workflow
  push:
    branches:
      - main

env:
  ANYPOINT_BASE_URL: "https://anypoint.mulesoft.com" # Base URL for Anypoint Platform
  ORG_ID: "f75678aa-ba06-4a02-a863-17caa791761e" # Replace with your Organization ID
  ENV_ID: "b126ed92-9bed-4496-8e31-160e24e375be" # Replace with your Environment ID
  TARGET_ID: "51295947" # Replace with your Target ID
  ARTIFACT_NAME: "rafiq-hybrid-cicd" # Replace with your Artifact Name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Generate Access Token
      id: generate-token
      run: |
        echo "Generating Access Token using Connected App credentials..."
        response=$(curl --request POST "$ANYPOINT_BASE_URL/accounts/api/v2/oauth2/token" \
          --header "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "client_id=${{ secrets.CLIENT_ID }}" \
          --data-urlencode "client_secret=${{ secrets.CLIENT_SECRET }}" \
          --data-urlencode "grant_type=client_credentials")
        echo "Response: $response" # Optional for debugging purposes; remove in production
        echo "TOKEN=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

    - name: Deploy MuleSoft API
      run: |
        echo "Deploying MuleSoft API..."
        curl --request POST "$ANYPOINT_BASE_URL/hybrid/api/v1/applications" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID" \
          --form "file=@test.jar" \
          --form "artifactName=$ARTIFACT_NAME" \
          --form "targetId=$TARGET_ID"
