name: Deploy MuleSoft APIs

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

env:
  ANYPOINT_BASE_URL: "https://anypoint.mulesoft.com/hybrid/api/v1/applications" # Base URL for Anypoint Platform
  ORG_ID: "f75678aa-ba06-4a02-a863-17caa791761e" # Replace with your Organization ID
  ENV_ID: "b126ed92-9bed-4496-8e31-160e24e375be" # Replace with your Environment ID
  TARGET_ID: "51295947" # Replace with your Target ID
  ARTIFACT_NAME: "rafiq-hybrid-cicd" # Replace with your Artifact Name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Generate Access Token
      id: generate-token
      run: |
        echo "Generating Access Token using Connected App credentials..."
        response=$(curl --request POST "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token" \
          --header "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "client_id=06c4c45cf75341509e5b9fb5497b7c2b" \
          --data-urlencode "client_secret=B51af0A705864943B92692AFbB1CC2db" \
          --data-urlencode "grant_type=client_credentials")
        echo "TOKEN=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

    - name: Check if API Exists
      id: check-api
      run: |
        echo "Checking if API already exists..."
        response=$(curl --request GET "$ANYPOINT_BASE_URL" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID")
        echo "Response: $response"
        exists=$(echo $response | jq -r --arg ARTIFACT_NAME "$ARTIFACT_NAME" '.data[] | select(.artifact.name == $ARTIFACT_NAME) | .id')
        if [ -n "$exists" ]; then
          echo "API_EXISTS=true" >> $GITHUB_ENV
          echo "API_ID=$exists" >> $GITHUB_ENV
        else
          echo "API_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Delete Existing API (if exists)
      if: env.API_EXISTS == 'true'
      run: |
        echo "Deleting existing API with ID: $API_ID..."
        curl --request DELETE "$ANYPOINT_BASE_URL/$API_ID" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID"
        echo "Existing API deleted successfully."

    - name: Deploy MuleSoft API
      run: |
        echo "Deploying MuleSoft API..."
        curl --request POST "$ANYPOINT_BASE_URL" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID" \
          --form "file=@test2.jar" \
          --form "artifactName=$ARTIFACT_NAME" \
          --form "targetId=$TARGET_ID"
