name: Deploy MuleSoft APIs

on:
  push:
    branches:
      - main

env:
  ANYPOINT_BASE_URL: "https://anypoint.mulesoft.com" # Base URL for Anypoint Platform
  ORG_ID: "f75678aa-ba06-4a02-a863-17caa791761e" # Organization ID
  ENV_ID: "b126ed92-9bed-4496-8e31-160e24e375be" # Environment ID
  TARGET_ID: "51295947" # Target ID
  ARTIFACT_NAME: "rafiq-hybrid-cicd" # Application/Artifact Name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Generate Access Token
      id: generate-token
      run: |
        echo "Generating Access Token using Connected App credentials..."
        response=$(curl --silent --request POST "$ANYPOINT_BASE_URL/accounts/api/v2/oauth2/token" \
          --header "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "client_id=06c4c45cf75341509e5b9fb5497b7c2b" \
          --data-urlencode "client_secret=B51af0A705864943B92692AFbB1CC2db" \
          --data-urlencode "grant_type=client_credentials")
        echo "TOKEN=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

    - name: Check if API Exists
      id: check-api
      run: |
        echo "Checking if the API exists..."
        response=$(curl --silent --request GET "$ANYPOINT_BASE_URL/hybrid/api/v1/applications" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID")
        echo "Response: $response"
        if echo "$response" | jq -e ".data[] | select(.name == \"$ARTIFACT_NAME\")" > /dev/null; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Delete Existing API (if exists)
      if: env.exists == 'true'
      run: |
        echo "Deleting existing API..."
        appId=$(curl --silent --request GET "$ANYPOINT_BASE_URL/hybrid/api/v1/applications" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID" | jq -r ".data[] | select(.name == \"$ARTIFACT_NAME\") | .id")
        curl --request DELETE "$ANYPOINT_BASE_URL/hybrid/api/v1/applications/$appId" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID"
        echo "Deleted application with ID: $appId"

    - name: Deploy MuleSoft API
      run: |
        echo "Deploying MuleSoft API..."
        curl --request POST "$ANYPOINT_BASE_URL/hybrid/api/v1/applications" \
          --header "Authorization: Bearer $TOKEN" \
          --header "X-ANYPNT-ORG-ID: $ORG_ID" \
          --header "X-ANYPNT-ENV-ID: $ENV_ID" \
          --form "file=@test.jar" \
          --form "artifactName=$ARTIFACT_NAME" \
          --form "targetId=$TARGET_ID"
